apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: dev
data:
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DATABASE_URL: "postgres://postgres:postgres123@postgres-service.dev.svc.cluster.local:5432/django_db"
  DATABASE_NAME: "django_db"
  DATABASE_HOST: "postgres-service.dev.svc.cluster.local"
  DATABASE_PORT: "5432"
  REDIS_URL: "redis://redis-service.dev.svc.cluster.local:6379/0"
  ALLOWED_HOSTS: "*"
  ENVIRONMENT: "development"
