apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: prod
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DATABASE_URL: "postgres://postgres:prodpassword456@postgres-service.prod.svc.cluster.local:5432/django_db"
  DATABASE_NAME: "django_db"
  DATABASE_HOST: "postgres-service.prod.svc.cluster.local"
  DATABASE_PORT: "5432"
  REDIS_URL: "redis://redis-service.prod.svc.cluster.local:6379/0"
  ALLOWED_HOSTS: "*"
  ENVIRONMENT: "production"
