apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: prod
type: Opaque
stringData:
  SECRET_KEY: "prod-secret-key-super-secure-change-this"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "prodpassword456"
