---
all:
  children:
    kubernetes:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    docker_containers:
      hosts:
        django_app:
          ansible_connection: docker
          ansible_docker_extra_args: "-H=unix:///var/run/docker.sock"
