apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: default
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DATABASE_URL: "postgres://postgres:postgres123@postgres-service:5432/django_db"
  DATABASE_NAME: "django_db"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  ALLOWED_HOSTS: "*"
